version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: daily
    default_labels:
      - dependencies
    automerged_updates:
      - match:
        update_type: all
        dependency_type: all
    allowed_updates:
      - match:
        update_type: all
    version_requirement_updates: increase_versions
